FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=ExpenseApp@1 \
    MYSQL_DATABASE=transactions

# Add SQL scripts to the container's entry point for initialization
ADD scripts/* /docker-entrypoint-initdb.d/
