FROM mysql:8.0
ENV  MYSQL_ROOT_PASSWORD=ExpenseApp@1 \
ADD scrpits/* .sql /docker-entrypoint-initdb.d
    # MYSQL_DATABASE=transations \
    # MYSQL_USER=Expense \
    # MYSQL_USER-PASSWORD=ExpenseApp@1 \

